In [0]:
import pandas as pd

In [0]:
# reading csv file from url
pos_sal=pd.read_csv('http://13.234.66.67/summer19/datasets/pos_sal.csv')

In [0]:
info=pd.read_csv('http://13.234.66.67/summer19/datasets/info.csv')

In [4]:
info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
Country      10 non-null object
Age          9 non-null float64
Salary       9 non-null float64
Purchased    10 non-null object
dtypes: float64(2), object(2)
memory usage: 400.0+ bytes


In [6]:
info.T

0      1        2      3  ...      6       7        8       9
Country    France  Spain  Germany  Spain  ...  Spain  France  Germany  France
Age            44     27       30     38  ...    NaN      48       50      37
Salary      72000  48000    54000  61000  ...  52000   79000    83000   67000
Purchased      No    Yes       No     No  ...     No     Yes       No     Yes

[4 rows x 10 columns]

In [15]:
#
X=info.iloc[:,0:4].values
X

array([['France', 44.0, 72000.0, 'No'],
       ['Spain', 27.0, 48000.0, 'Yes'],
       ['Germany', 30.0, 54000.0, 'No'],
       ['Spain', 38.0, 61000.0, 'No'],
       ['Germany', 40.0, nan, 'Yes'],
       ['France', 35.0, 58000.0, 'Yes'],
       ['Spain', nan, 52000.0, 'No'],
       ['France', 48.0, 79000.0, 'Yes'],
       ['Germany', 50.0, 83000.0, 'No'],
       ['France', 37.0, 67000.0, 'Yes']], dtype=object)

In [0]:
# removing missing value or replacing missing value with some relevent data
# info.describe()
from sklearn.preprocessing import Imputer

In [9]:
imp=Imputer(missing_values='NaN',axis=0,strategy='mean')

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [0]:
# this is only fitting of columns that we want to proces
impute=imp.fit(X[:,1:3])

In [0]:
# time for transforming the fitted column
X[:,1:3]=impute.transform(X[:,1:3])

In [22]:
X

array([['France', 44.0, 72000.0, 'No'],
       ['Spain', 27.0, 48000.0, 'Yes'],
       ['Germany', 30.0, 54000.0, 'No'],
       ['Spain', 38.0, 61000.0, 'No'],
       ['Germany', 40.0, 63777.77777777778, 'Yes'],
       ['France', 35.0, 58000.0, 'Yes'],
       ['Spain', 38.77777777777778, 52000.0, 'No'],
       ['France', 48.0, 79000.0, 'Yes'],
       ['Germany', 50.0, 83000.0, 'No'],
       ['France', 37.0, 67000.0, 'Yes']], dtype=object)

In [0]:
# String label int/float
from sklearn.preprocessing import LabelEncoder

In [0]:
# this is for country labeling
cont=LabelEncoder()

In [0]:
# Now apply column first in this labelEn
X[:,0]=cont.fit_transform(X[:,0])

In [26]:
X

array([[0, 44.0, 72000.0, 'No'],
       [2, 27.0, 48000.0, 'Yes'],
       [1, 30.0, 54000.0, 'No'],
       [2, 38.0, 61000.0, 'No'],
       [1, 40.0, 63777.77777777778, 'Yes'],
       [0, 35.0, 58000.0, 'Yes'],
       [2, 38.77777777777778, 52000.0, 'No'],
       [0, 48.0, 79000.0, 'Yes'],
       [1, 50.0, 83000.0, 'No'],
       [0, 37.0, 67000.0, 'Yes']], dtype=object)

In [0]:
# labeling last column
ans=LabelEncoder()

In [0]:
X[:,-1]=ans.fit_transform(X[:,-1])

In [29]:
X

array([[0, 44.0, 72000.0, 0],
       [2, 27.0, 48000.0, 1],
       [1, 30.0, 54000.0, 0],
       [2, 38.0, 61000.0, 0],
       [1, 40.0, 63777.77777777778, 1],
       [0, 35.0, 58000.0, 1],
       [2, 38.77777777777778, 52000.0, 0],
       [0, 48.0, 79000.0, 1],
       [1, 50.0, 83000.0, 0],
       [0, 37.0, 67000.0, 1]], dtype=object)

In [0]:
# Now encoding First Column i.e. making subcolumn of first column
from sklearn.preprocessing import OneHotEncoder

In [0]:
# defining exact column number where we want to make category
firstcl=OneHotEncoder(categorical_features=[0])

In [33]:

# After transforming we need to convert into numpy array
X=firstcl.fit_transform(X).toarray() 

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [35]:
# To show in int only
X.astype(int)

array([[    1,     0,     0,    44, 72000,     0],
       [    0,     0,     1,    27, 48000,     1],
       [    0,     1,     0,    30, 54000,     0],
       [    0,     0,     1,    38, 61000,     0],
       [    0,     1,     0,    40, 63777,     1],
       [    1,     0,     0,    35, 58000,     1],
       [    0,     0,     1,    38, 52000,     0],
       [    1,     0,     0,    48, 79000,     1],
       [    0,     1,     0,    50, 83000,     0],
       [    1,     0,     0,    37, 67000,     1]])